INSERT INTO items (description, price) VALUES('Panasonic', 800);
INSERT INTO items (description, price) VALUES('Sony', 700);
INSERT INTO items (description, price) VALUES('Apple', 1000);
INSERT INTO items (description, price) VALUES('Sony Notebook', 1000);
INSERT INTO items (description, price) VALUES('Hewlett Packard', 500);
INSERT INTO items (description, price) VALUES('Bianchi', 600);
INSERT INTO items (description, price) VALUES('Nike', 100);
INSERT INTO items (description, price) VALUES('Adidas', 200);
INSERT INTO items (description, price) VALUES('Reebok', 300);
INSERT INTO items (description, price) VALUES('Chino Panasonic', 400);
INSERT INTO items (description, price) VALUES('TenoSony', 300);
INSERT INTO items (description, price) VALUES('Banaana', 400);
INSERT INTO items (description, price) VALUES('TenoSony Notebook', 6000);
INSERT INTO items (description, price) VALUES('HP', 500);
INSERT INTO items (description, price) VALUES('Assis', 600);
INSERT INTO items (description, price) VALUES('confor', 100);
INSERT INTO items (description, price) VALUES('Maraton', 200);
INSERT INTO items (description, price) VALUES('Cumbre', 300);
